export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST'
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS'
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE'

export const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST'
export const ADD_ENTRY_SUCCESS = 'ADD_ENTRY_SUCCESS'
export const ADD_ENTRY_FAILURE = 'ADD_ENTRY_FAILURE'

export const REMOVE_ENTRY_REQUEST = 'REMOVE_ENTRY_REQUEST'
export const REMOVE_ENTRY_SUCCESS = 'REMOVE_ENTRY_SUCCESS'
export const REMOVE_ENTRY_FAILURE = 'REMOVE_ENTRY_FAILURE'

export const TOGGLE_ENTRY_COMPLETION_REQUEST = 'TOGGLE_ENTRY_COMPLETION_REQUEST'
export const TOGGLE_ENTRY_COMPLETION_SUCCESS = 'TOGGLE_ENTRY_COMPLETION_SUCCESS'
export const TOGGLE_ENTRY_COMPLETION_FAILURE = 'TOGGLE_ENTRY_COMPLETION_FAILURE'
