export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST'
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS'
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE'

export const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST'
export const ADD_ENTRY_SUCCESS = 'ADD_ENTRY_SUCCESS'
export const ADD_ENTRY_FAILURE = 'ADD_ENTRY_FAILURE'

export const REMOVE_ENTRY_REQUEST = 'REMOVE_ENTRY_REQUEST'
export const REMOVE_ENTRY_SUCCESS = 'REMOVE_ENTRY_SUCCESS'
export const REMOVE_ENTRY_FAILURE = 'REMOVE_ENTRY_FAILURE'

export const CONSTANT_NAME_REQUEST = 'CONSTANT_NAME_REQUEST'
export const CONSTANT_NAME_SUCCESS = 'CONSTANT_NAME_SUCCESS'
export const CONSTANT_NAME_FAILURE = 'CONSTANT_NAME_FAILURE'
