export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST'
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS'
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE'

export const CONSTANT_NAME_REQUEST = 'CONSTANT_NAME_REQUEST'
export const CONSTANT_NAME_SUCCESS = 'CONSTANT_NAME_SUCCESS'
export const CONSTANT_NAME_FAILURE = 'CONSTANT_NAME_FAILURE'
