export const SELECT_LIST_REQUEST = 'SELECT_LIST_REQUEST';
export const SELECT_LIST_SUCCESS = 'SELECT_LIST_SUCCESS';

export const FETCH_ALL_LISTS_REQUEST = 'FETCH_ALL_LISTS_REQUEST';
export const FETCH_ALL_LISTS_SUCCESS = 'FETCH_ALL_LISTS_SUCCESS';
export const FETCH_ALL_LISTS_FAILURE = 'FETCH_ALL_LISTS_FAILURE';

export const FETCH_SINGLE_LIST_REQUEST = 'FETCH_SINGLE_LIST_REQUEST';
export const FETCH_SINGLE_LIST_SUCCESS = 'FETCH_SINGLE_LIST_SUCCESS';
export const FETCH_SINGLE_LIST_FAILURE = 'FETCH_SINGLE_LIST_FAILURE';

export const MODIFY_LIST_REQUEST = 'MODIFY_LIST_REQUEST';
export const MODIFY_LIST_SUCCESS = 'MODIFY_LIST_SUCCESS';
export const MODIFY_LIST_FAILURE = 'MODIFY_LIST_FAILURE';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const REMOVE_TASK_REQUEST = 'REMOVE_TASK_REQUEST';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILURE = 'REMOVE_TASK_FAILURE';

export const TOGGLE_TASK_COMPL_REQUEST = 'TOGGLE_TASK_COMPLETION_REQUEST';
export const TOGGLE_TASK_COMPL_SUCCESS = 'TOGGLE_TASK_COMPLETION_SUCCESS';
export const TOGGLE_TASK_COMPL_FAILURE = 'TOGGLE_TASK_COMPLETION_FAILURE';

export const CHANGE_TASK_ORDER_REQUEST = 'CHANGE_TASK_ORDER_REQUEST';
export const CHANGE_TASK_ORDER_SUCCESS = 'CHANGE_TASK_ORDER_SUCCESS';
export const CHANGE_TASK_ORDER_FAILURE = 'CHANGE_TASK_ORDER_FAILURE';

export const CONSTANT_NAME_REQUEST = 'CONSTANT_NAME_REQUEST';
export const CONSTANT_NAME_SUCCESS = 'CONSTANT_NAME_SUCCESS';
export const CONSTANT_NAME_FAILURE = 'CONSTANT_NAME_FAILURE';
