export const FETCH_LISTS_REQUEST = 'FETCH_LISTS_REQUEST'
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS'
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE'

export const CONSTANT_NAME_REQUEST = 'CONSTANT_NAME_REQUEST'
export const CONSTANT_NAME_SUCCESS = 'CONSTANT_NAME_SUCCESS'
export const CONSTANT_NAME_FAILURE = 'CONSTANT_NAME_FAILURE'
