export const FETCH_LISTS_REQUEST = 'FETCH_LISTS_REQUEST'
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS'
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE'

export const MODIFY_LIST_REQUEST = 'MODIFY_LIST_REQUEST'
export const MODIFY_LIST_SUCCESS = 'MODIFY_LIST_SUCCESS'
export const MODIFY_LIST_FAILURE = 'MODIFY_LIST_FAILURE'

export const CONSTANT_NAME_REQUEST = 'CONSTANT_NAME_REQUEST'
export const CONSTANT_NAME_SUCCESS = 'CONSTANT_NAME_SUCCESS'
export const CONSTANT_NAME_FAILURE = 'CONSTANT_NAME_FAILURE'